### ISSUE TITLE
Version 2018.1.10 damages fileUploadNode

### ISSUE THREAD

**Issue by ryppo** [JPro-one/JPro-tickets#14] opened 2019-01-11 09:36 UTC
Hi, 
I guess there is something broken is 2018.1.10. The feature
`FileUploader fileUploadButton = WebAPI.getWebAPI(gui().getWorkbench().getScene()).makeFileUploadNode(myNode);`
does not provide the same result as in 1.9.
Using these switches,
- `fileUploadButton.setSelectFileOnClick(true)`
- `fileUploadButton.setSelectFileOnDrop(true)`
do **not throw an event** to these listeners:
`fileUploadButton.selectedFileProperty().addListener((observable, oldValue, newValue) -> {
				fileUploadButton.uploadFile();
			});
fileUploadButton.uploadedFileProperty().addListener((observable, oldValue, newValue) -> {
				processTheFile(newValue);
			});`

If I jump back from 2018.1.10 to 2018.1.9 it works fine again.

**Comment by FlorianKirmaier** [comment] 2019-01-11 13:54
@ryppo 
Thank you for the report!
It's indeed a bug introduced in `2018.1.10`. 
The cause also introduced a bug, related to text-selection.
The bug is already fixed.
The fix is available in the version `2018.1.11-SNAPSHOT`.

**Comment by ryppo** [comment] 2019-01-22 14:02
I confirm, the bug is fixed. Thx.
@FlorianKirmaier  What will be content of 2018.1.11, and when will it be released?

**Comment by FlorianKirmaier** [comment] 2019-01-22 15:40
@ryppo
It will be released at the begin of February.
It will contain some further bugfixes and performance improvements.

After 2018.1.11, we will focus on new features, like Canvas-support and support for Stages.

**Comment by FlorianKirmaier** [comment] 2019-02-11 14:37
The new version is now officially released, so I'm closing the ticket.

**Closed by FlorianKirmaier** 2019-02-11 14:37 UTC
