### ISSUE TITLE
WebApi.OpenStageAsTab question

### ISSUE THREAD

**Issue by Hugolarson** [JPro-one/JPro-tickets#74] opened 2020-08-20 11:58 UTC
Hi.
Is it possible to keep track on stages opened with WebApi.OpenStageAsTab?
For example I want to show a PDF with WebApi.OpenStageAsTab but also only want ONE such tab open in the application.

Thanks

**Comment by FlorianKirmaier** [comment] 2020-08-27 09:23
That's currently not possible. 
Especially checking whether a tab with a PDF is open, is close to impossible.
I don't think there is an API to inform you when a specific tab is closed.

What is possible, is to communicate between different tabs of the same JPro-server.
But that's uncommon, which is the reason we don't have any samples for it, and it would be a bit complicated to implement.
I wouldn't recommend it.

**Comment by Hugolarson** [comment] 2020-08-27 09:59
I would be nice of JPRO could fire a Stage.CLOSED event if the tab is closed.

**Comment by FlorianKirmaier** [comment] 2020-08-27 12:20
Okay, the pdf-part confused me a bit.
The easiest way to accomplish that would be to add a "close listener" to the stage itself.
Currently, JPro keeps the session open for a short time, for the case of a reconnect, but that isn't useful when the tab was explicitly closed.

**Comment by Hugolarson** [comment] 2020-09-08 04:11
I tried **stage.setOnHidden(e -> System.out.println("  closed ");** and there is a delay and seems to behave like **getWebAPI().addInstanceCloseListener**. Please correct me if i'm wrong.

In the JPro console when stage is opened or closed a text about it is printed immediately.
Is it possible to listen to this event?

**Comment by FlorianKirmaier** [comment] 2020-09-14 15:19
Yes it behaves the same. The problem is not, that these listener are wrong. The problem is, that JPro handles closed tabs and "disconnects" the same. In both cases JPro waits some time to wait for a reconnect. But this is not useful when the tab is closed, because no reconnect is possible. 

The easiest way to solve your problem would be, to optimize how JPro handles closed tabs.
It wouldn't require any new API, optimizes some behavior, and would solve your problem.

**Comment by Hugolarson** [comment] 2021-01-12 03:02
Hello,
Is there a way to invalidate and garbage collect a Stage opened as tab?
In normal FX just close the Stage. Any alternative in JPro?

**Comment by FlorianKirmaier** [comment] 2021-01-12 12:15
Just close the tab and wait for a short moment, and it should be garbage collected. 
It's basically the same as normal JavaFX
I think that should work well. 
Maybe tell me more about your scenario. It might help me understand what might help you.

**Comment by Hugolarson** [comment] 2021-01-12 15:17
Sorry I meant to do it programmatically. Maybe with a timer.

**Comment by FlorianKirmaier** [comment] 2021-01-12 15:30
We can't close the tab in the browser for technical reasons. A simple workaround might be to replace the Scene with an empty scene. This way, the original scene gets collected, and the memory usage is close to zero.
MIght be possible to add it to the WebAPI to close the current application, but that's very rarely what is wanted.

**Comment by Hugolarson** [comment] 2021-03-18 06:45
There is dramatic change of OpenStageAsTab in version 2020.1.4.

When stage opened as tab and then closed its partly shown in the main  tab/stage it was open from.

"[info] c.j.i.s.ViewInfo$ - Application closed:" is instantly shown when sub stage is closed. Here closed stage UI is partly shown on main stage.
After some seconds "[info] c.j.i.c.InstanceImpl - closing window!" Main stage is back to normal.

Some how closing sub tab cause lock on main stage until "[info] c.j.i.c.InstanceImpl - closing window" (takes seconds)

Also why is there second delay between "[info] c.j.i.s.ViewInfo$ - Application closed:" and [info] c.j.i.c.InstanceImpl - closing window!"?

**Comment by FlorianKirmaier** [comment] 2021-03-18 14:30
Thank you for the bug-report.
JPro now has some support to add Stages into the Application without opening a new tab, when the owner of the Stage is set. It seems like, this feature somehow conflicts with openStageAsTab. We will swiftly create a fix for it, and provide a new JPro Version.

**Comment by Hugolarson** [comment] 2021-03-18 14:38
Maybe you you can make some examples of the new features? The Jpro javadoc is sometimes too few worded :)

**Comment by FlorianKirmaier** [comment] 2021-03-18 14:47
You are right.
For a small demo, you can take a look in our new demo-website: https://www.jfx-ensemble.com/?page=sample/dockfx/DockFX
It shows the use of an existing DockingFramework, which now works with JPro.
The short-term plan is to add more samples to https://github.com/jpro-one/jpro-samples and integrate them into the new ensemble-website.

**Comment by FlorianKirmaier** [comment] 2021-03-19 16:59
@Hugolarson 
We've made a new SNAPSHOT build 2020.1.5-SNAPSHOT, in this version, openStageAsTab throws an IllegalStateException, when it's called with a Stage with an owner. The fix for your problem is to just not set the owner when JPro is Used and you want to open the Stage as a Tab.

**Comment by Hugolarson** [comment] 2021-03-21 06:43
I set stage owner to null and it now works but this exception is always thrown:
The stage owner is NOT set after show is called.

java.lang.IllegalStateException: Cannot set owner once stage has been set visible
        at javafx.stage.Stage.initOwner(Stage.java:552)
        at simplefx.stage.packageTrait$StageExtension.$anonfun$ownerBindable$5(packageTraitStage.scala:21)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at simplefx.cores.interfaces.parts.CoreTypesEvent$EventLikeAlternateSignature.$anonfun$$minus$minus$greater$1(CoreTypesEvent.scala:16)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl.$anonfun$trigger$2(CoreTypesBindable.scala:192)
        at simplefx.cores.interfaces.parts.CoreTypesDisposer.withDetectDisposer(CoreTypesDisposer.scala:65)
        at simplefx.cores.interfaces.parts.CoreTypesDisposer.withDetectDisposer$(CoreTypesDisposer.scala:63)
        at simplefx.cores.standard.Core.withDetectDisposer(Core.scala:9)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl.$anonfun$trigger$1(CoreTypesBindable.scala:191)
        at simplefx.cores.interfaces.parts.CoreTypesGetter.withGetter(CoreTypesGetter.scala:12)
        at simplefx.cores.interfaces.parts.CoreTypesGetter.withGetter$(CoreTypesGetter.scala:10)
        at simplefx.cores.standard.Core.withGetter(Core.scala:9)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl.trigger(CoreTypesBindable.scala:190)
        at simplefx.cores.interfaces.parts.CoreTypesEvent$EventLike.$minus$minus$greater(CoreTypesEvent.scala:25)
        at simplefx.cores.interfaces.parts.CoreTypesEvent$EventLike.$minus$minus$greater$(CoreTypesEvent.scala:25)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl.$minus$minus$greater(CoreTypesBindable.scala:24)
        at simplefx.cores.interfaces.parts.CoreTypesEvent$EventLikeAlternateSignature.$minus$minus$greater(CoreTypesEvent.scala:16)
        at simplefx.stage.packageTrait$StageExtension.$anonfun$ownerBindable$2(packageTraitStage.scala:21)
        at simplefx.cores.interfaces.parts.CoreTypesDisposer.withDetectDisposer(CoreTypesDisposer.scala:65)
        at simplefx.cores.interfaces.parts.CoreTypesDisposer.withDetectDisposer$(CoreTypesDisposer.scala:63)
        at simplefx.cores.standard.Core.withDetectDisposer(Core.scala:9)
        at simplefx.stage.packageTrait$StageExtension.$anonfun$ownerBindable$1(packageTraitStage.scala:10)
        at simplefx.cores.interfaces.parts.CoreTypesGetter.withGetter(CoreTypesGetter.scala:12)
        at simplefx.cores.interfaces.parts.CoreTypesGetter.withGetter$(CoreTypesGetter.scala:10)
        at simplefx.cores.standard.Core.withGetter(Core.scala:9)
        at simplefx.stage.packageTrait$StageExtension.ownerBindable$lzycompute(packageTraitStage.scala:10)
        at simplefx.stage.packageTrait$StageExtension.ownerBindable(packageTraitStage.scala:10)
        at simplefx.stage.packageTrait$StageExtension.owner(packageTraitStage.scala:10)
        at com.jpro.WebAPIImpl$.registerStage(WebAPIImpl.scala:44)
        at com.jpro.WebAPIImpl$ExtendStage$$anon$1.openStageAsTab(WebAPIImpl.scala:296)

**Comment by FlorianKirmaier** [comment] 2021-03-21 21:22
Thank you for reporting the exception. We've made a new version of 2020.1.5-SNAPSHOT, now no more exception should be thrown.

**Comment by Hugolarson** [comment] 2021-03-22 06:15
It works now.

When closing a tab this is instantly shown. Is there a way to capture this in a event?
[info] c.j.i.s.ViewInfo$ -
[info] c.j.i.s.ViewInfo$ - Application closed:
[info] c.j.i.s.ViewInfo$ - startTime      : Mon Mar 22 07:10:40 CET 2021
[info] c.j.i.s.ViewInfo$ - averageLatency : 00:00:00.025
[info] c.j.i.s.ViewInfo$ - averageJitter  : 00:00:00.041
[info] c.j.i.s.ViewInfo$ - framerateServer: 00:00:00.000
[info] c.j.i.s.ViewInfo$ - framerateClient: 00:00:00.000
[info] c.j.i.s.ViewInfo$ - raw            : 247283
[info] c.j.i.s.ViewInfo$ - zipped         : 26439
[info] c.j.i.s.ViewInfo$ -

------------------This takes a some seconds-----------
[info] c.j.i.c.InstanceImpl - closing window!

**Comment by Hugolarson** [comment] 2021-03-24 01:58
Something is messed up with MouseEvent or Events in general in version 2020.1.4 and 5. Don't know if it's a feature or bug.

I capture mouse events to keep track on status of tabs and somehow panes trigger events that do not belong.

**Comment by FlorianKirmaier** [comment] 2021-03-24 09:16
In the next (major) version, we will distinguish between a disconnect, and closing a tab explicitly. This will allow us to close the window instantly, which well be accessible to you, by listening to the showing event of the Stage.

**Comment by Hugolarson** [comment] 2021-03-24 09:48
Great!

**Comment by Hugolarson** [comment] 2022-05-06 02:04
> In the next (major) version, we will distinguish between a disconnect, and closing a tab explicitly. This will allow us to close the window instantly, which well be accessible to you, by listening to the showing event of the Stage.

Hello,
Any news regarding this?
BR, Hugo

**Comment by FlorianKirmaier** [comment] 2022-05-07 16:48
This works now.
I assume you commented because we didn't close the ticket.
We've just verified that it works reliably.
If it doesn't work in some setup, please create a new Ticket with more details.

**Closed as completed by FlorianKirmaier** 2022-05-07 16:48 UTC
