### ISSUE TITLE
JPro Release Maven Powershell issue on windows.

### ISSUE THREAD

**Issue by nyzzik** [JPro-one/JPro-tickets#184] opened 2024-08-28 16:49 UTC
Hello, I am utilizing the jpro plugin for maven and it seems that whenever I create a release, the powershell script that is created and place into the bin folder uses backslash `\` in order to escape the quotes `"` however in powershell, at least for windows, the backtick `` ` `` is used to escape quotes. So in order to allow this powershell script to run on windows, i need to replace all the backslashes with backticks

Another question, unrelated to the previous concern, would it be possible to allow for the jpro release to output a folder with the folders inside of it rather than the zip? I am creating an installer utilizing the jpro release however i do not need it zipped, so for my current use case i have to run `mvn jpro:release` then unzip the release and then load it into my installer.

**Comment by besidev** [comment] 2024-08-29 09:54
Hello @nyzzik.

We have just released JPro version `2024.3.2` containing some bug fixes regarding paths handling in general in the plugins, especially on Windows. Please give it a try and let us know if the issue still persists.

Regarding the other topic we can consider adding an option to `not` produce a release `zip` file when `jpro:release` is called, but just the folder containing all the stuff inside it. In the meantime easily create a script to unzip it automatically.

**Comment by nyzzik** [comment] 2024-09-10 20:50
After upgrading to the version `2024.3.2` the start.ps1 contained in the bin folder after running `jpro:release` is still using `\` to escape quotes rather than `` ` ``

Regarding the second topic, thats what I am currently doing, it just seems unnecessary hence asking for the feature.

**Comment by besidev** [comment] 2024-10-24 15:41
Hi @nyzzik Josh,

Can you please check the new snapshot build we have just released, JPro version `2024.3.4-SNAPSHOT`. We have reviewed and updated the starting script on Windows to use single-quotes and some other improvements. Please give it try and let us know if it works. It will be great to know that we now fixed this issue before publishing the next release.

Thank you,
Besmir

**Comment by besidev** [comment] 2024-11-05 14:02
We just released JPro version `2024.4.0`. Give it a try and let us know if the issue is now fixed.

**Comment by besidev** [comment] 2024-11-11 10:58
I'm closing this ticket. I'f the issue still persist, you can re-open it or just create a new one.

**Closed as completed by besidev** 2024-11-11 10:58 UTC
