### ISSUE TITLE
JFoenix pop not working in when fullscreen is false with 2019.1.1

### ISSUE THREAD

**Issue by vewert** [JPro-one/JPro-tickets#29] opened 2019-08-13 17:13 UTC
I was playing around with the HelloJPro sample, and tried adding a JFoenix pop up. I could get it to work when my `index.html` had `fullscreen="true"`, but when I set it to `fullscreen="false"` the popup was no longer displayed.

This is happening with JPro version 2019.1.1. When I switched back to version 2018.1.14, I was able to get a JFoenix popup to work with fullscreen set to either true or false. Is this expected behaviour?

I am using Java 11 (11.0.4) and JavaFX 11.0.2

Thanks for your help.

**Comment by FlorianKirmaier** [comment] 2019-08-14 15:49
Thank you for the report.
When i check our [JFoenix-online demo](https://demos.jpro.one/jfoenix.html), I can't find anything not working.

Can you be a bit more specific on what's not working?
 - What class are you using?
 - which version of JFoenix are you using?
 - Can you provide us with a simple program, which reproduces the problem?
Most ideally would be project which reproduces the problem.
This way, we would be able to fix the problem very quick.

It's also strange, that this bug depends on the fullscreen - configuration.
Maybe the Popup is rendered in the center of the page?

**Comment by vewert** [comment] 2019-08-14 17:53
Thank-you for your prompt reply.

I was using JFoenix 9.0.8, now tried 9.0.9 with the same result. I am using JFoenix `JXDialog` class.

I have attached my sample project, which uses HelloJPro as its start.

[HelloJPro.zip](https://github.com/JPro-one/JPro-tickets/files/3502581/HelloJPro.zip)

Basically, when running, the UI has a TextField and two Buttons. Clicking Save, saves a file, named with the value in the TextField, and then displays the JFoenix JXDialog popup, with some information, including the location where the file was saved.

As mentioned, when running with `fullscreen="true"`, the popup is displayed, as expected, but when I set `fullscreen="false"`, the UI get greyed out/disabled, but no popup is displayed.

The strange thing is, if I switch JPro to version 2018.1.14, and try it again, the Popup is displayed in both cases.

I have also attached a short video clip, showing how it works, when using JPro 2018.1.14 and fullscreen set to `false`.

[demo.zip](https://github.com/JPro-one/JPro-tickets/files/3502591/demo.zip)

**Comment by FlorianKirmaier** [comment] 2019-08-18 13:14
Thank you for the report.
I was able to verify this problem.
It doesn't seem to happen on all browsers. It works for me on Chrome, but I was able to reproduce the problem on Firefox. Interestingly, it doesn't happen when the developer mode is enabled.

**Comment by FlorianKirmaier** [comment] 2019-08-23 14:32
Something similar happens in the popups sample: https://github.com/JPro-one/JPro-Samples
The popup doesn't show, but more interestingly - the JFoenixButton isn't visible on Firefox (until the  inspector is opened)

**Comment by FlorianKirmaier** [comment] 2019-08-23 15:39
The bugs seems to be non-deterministic. Sometimes it seems to work.
It's probably a bug in firefox.
FireFox Version 69 und 58 are affected by this. Version 48 seems to work.

**Comment by FlorianKirmaier** [comment] 2019-09-05 09:18
The next minor release - which will be released soon, will contain a fix for this problem.

**Comment by FlorianKirmaier** [comment] 2019-09-11 13:24
fixed in 2019.1.2

**Closed by FlorianKirmaier** 2019-09-11 13:24 UTC
