### ISSUE TITLE
Is there is a why to set nodeOrientationProperty of Javafx on Jpro.one web?

### ISSUE THREAD

**Issue by ctoabidmaqbool** [JPro-one/JPro-tickets#112] opened 2021-10-26 12:07 UTC
I am trying to set nodeOrientationProperty(), but in generated Jpro.one webpage it's totally not affecting.

Is there any method / trick I can't use to solve the problem?

In languages that's are right-to-left I mostly use this trick but in here this is not working.

**Comment by FlorianKirmaier** [comment] 2021-10-29 09:13
Hm, It's new to me, that there is a problem with nodeOrientation. To my knowledge, there shouldn't be a problem - especially because JPro doesn't change anything in the behavior for nodeOrientation.

Can you share a sample program, while illustrates the problem? Then we can check whether there is a difference between JPro-Javafx and desktop-Javafx.

**Comment by ctoabidmaqbool** [comment] 2021-11-02 04:26
@FlorianKirmaier I have made a simple test where I have used Urdu Language (Pakistani National Language) & Right to Left Layout to demonistrate the issue>
https://github.com/Maqbool-Solutions-SMC-Pvt-Ltd/JPro-Orientation-Test [sample is made using latest HelloJpo project]

* Desktop View screenshot form scene-builder
![image](https://user-images.githubusercontent.com/10474725/139786687-f649f010-93a1-4c4d-a78f-3264620f7b08.png)

* JPro-one webapp, screenshot form web browser, (chrome)
![image](https://user-images.githubusercontent.com/10474725/139786767-92194d31-4980-49c0-9c04-00c0436f2091.png)

**Comment by FlorianKirmaier** [comment] 2021-11-02 12:46
thank you for the program! 
we will take a look into it.
it seems that both, the node orientation is ignored, and there are some text rendering issues.

**Comment by FlorianKirmaier** [comment] 2021-11-03 23:01
Can you test our latest SNAPSHOT build `2021.2.1-SNAPSHOT`?
This should fix both the rendering of "Right To Left Text" and properly implements the `Node.nodeOrientation` property.

**Comment by ctoabidmaqbool** [comment] 2021-11-04 11:05
@FlorianKirmaier `2021.2.1-SNAPSHOT` this solved the problem, but still little problem are exists.
You can see difference clear in my another commercial project.

* This is an image of desktop running app (windows 10) using jpro option `visible = true` in build.gradle file
   ![image](https://user-images.githubusercontent.com/10474725/140303289-58952193-7ecc-4927-a73e-58db2d4bbd15.png)


* This is an image of same app running on web (chrome), 
   ![image](https://user-images.githubusercontent.com/10474725/140303546-743637da-5c71-4cac-a76a-3931de8f27a8.png)

Using latest jpro version `2021.2.0` the problem was much more, but this time it's little

**Comment by FlorianKirmaier** [comment] 2021-11-04 11:19
I notice 2 differences - the text in the center seems different, and at the top bar, the order of the texts seems different.
Looks like it's ignoring the nodeOrientation for this specific element.
Can you try to create another sample program, which reproduces the problem?
Then we should be able to fix it.

**Comment by ctoabidmaqbool** [comment] 2021-11-04 11:19
@FlorianKirmaier There is another little problem, of font/text position / arrangement on webapp, mybe I have to mention this in another issue. Let see the different>

Desktop Running in Windows 10 e.g. jpro option `visable = true` in `build.gradle` file
![Screenshot (943)](https://user-images.githubusercontent.com/10474725/140304609-316afe4e-aa51-41f8-9435-a955be13c323.png)

Webapp running in Chrome under window 10
![Screenshot (944)](https://user-images.githubusercontent.com/10474725/140304709-df427eb3-91c4-42dd-b9bf-51a61bf119ad.png)

 Over all jpro.one technology is cool & much appreciated, also support team is awesome, love it!

**Comment by ctoabidmaqbool** [comment] 2021-11-04 12:28
@FlorianKirmaier I have commented just now at https://github.com/Maqbool-Solutions-SMC-Pvt-Ltd/JPro-Orientation-Test

I think, Right-To-Left for label is still not resolved.

Desktop View (Windows 10)
![Screenshot (949)](https://user-images.githubusercontent.com/10474725/140311846-76b414f8-1a4c-4e85-b0c3-60003ebceff2.png)

Webview (Chrome)
![Screenshot (951)](https://user-images.githubusercontent.com/10474725/140311914-fe6e9eca-3e86-4df9-a475-f14e317c1649.png)

Another issue combo-box is showing two popup boxes
![image](https://user-images.githubusercontent.com/10474725/140313317-0cecf1b5-3126-4837-a484-748aa4ee0951.png)

**Comment by FlorianKirmaier** [comment] 2021-11-04 15:43
I think the two popups are happening, because of "visible = true", there was the application window in the background.

Hm, the wrong rendered text is a bit tricky. When copying the wrongly rendered texts somewhere, they often get transformed in a similar way.

**Comment by ctoabidmaqbool** [comment] 2021-11-06 04:43
@FlorianKirmaier Noop! I have not copy paste Urdu text from any other source, rather write own by install Urdu keyboard layout e.g. `Pak Urdu Installer`

The problem with `Urdu` fonts here is that's jpro-web is not using Right-To-Left for these fonts. Moreover see here, in Windows everything is just work fine 100%.

![image](https://user-images.githubusercontent.com/10474725/140598200-6a34c308-e72a-4149-9a5c-3036200592aa.png)

however jpro issue, 
![image](https://user-images.githubusercontent.com/10474725/140598264-f9798ce0-7c65-4494-a87f-9f21751ae5e2.png)


And yeah, Combo-box have not any issue, duplicate is showing due to `visible = true` for another windows

**Comment by ctoabidmaqbool** [comment] 2021-11-06 05:36
@FlorianKirmaier Okey, here is another Urude text Rendereing issue: https://github.com/Maqbool-Solutions-SMC-Pvt-Ltd/JPro-Orientation-Test/commit/c0f39b1bb1dec8fd0de84028b3cae0315d588de4

On web (chrome)
![Screenshot (955)](https://user-images.githubusercontent.com/10474725/140599197-5b9e0486-50a3-4655-9d15-d9c34deaf3db.png)

Self App (Windos 10)
![Screenshot (957)](https://user-images.githubusercontent.com/10474725/140599200-30f98852-fc6c-4cb3-bc98-50d062bc2397.png)

**Comment by FlorianKirmaier** [comment] 2021-11-06 18:32
Thank you for the updated Bugreport!
I've got a new SNAPSHOT version for you to test.
We've investigated a bit more with RTL texts, and it also fixes your latest bug report.
Can you retest this version? I've got a good feeling about this version.


You might want to check the build-time from the /status page, it should be the following: `"JPro build time" : "2021-11-06T19:24:36.398484+01:00[Europe/Berlin]",` (or newer)

Ironically, I get various rendering issues with the original JavaFX version.
<img width="197" alt="Screenshot 2021-11-06 at 19 30 27" src="https://user-images.githubusercontent.com/6547435/140620136-06d053b1-4af7-4d77-8f58-98d6d15a786a.png">

**Comment by ctoabidmaqbool** [comment] 2021-11-07 04:47
@FlorianKirmaier Thank a lot, your latest `2021.2.1-SNAPSHOT` solve all problem related to `NodeOrientation` & `RightToLeft` issue for `RTL Languages`. Much appreciated

**Comment by ctoabidmaqbool** [comment] 2021-11-08 05:29
@FlorianKirmaier Hi! I have comment again at https://github.com/Maqbool-Solutions-SMC-Pvt-Ltd/JPro-Orientation-Test/commit/3f6d3535aa8fbaea8eef88bbe1a518e6ac79c96d with another issue e.g. Some fonts not looks great at web pages e.g. padding / margin / spacing problem.

Let see the difference:

At web page (chrome)
![Screenshot (960)](https://user-images.githubusercontent.com/10474725/140688994-67a94f20-f1d2-4d6b-9d4d-953a2f188dda.png)

Desktop (Windows 10)
![Screenshot (959)](https://user-images.githubusercontent.com/10474725/140689030-12ac65b2-e911-4ff8-bf42-3df2b040fa7f.png)

**Comment by FlorianKirmaier** [comment] 2021-11-15 13:16
fixed in 2021.2.1 (which was verified by the reporter on a SNAPSHOT build)

I've moved the other issue into a new issue.

**Closed as completed by FlorianKirmaier** 2021-11-15 13:16 UTC
